steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/course-planner-02/backend:latest', '-f', 'backend/Dockerfile', '.']
    dir: backend

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/course-planner-02/frontend:latest', '-f', 'frontend/Dockerfile', '.']
    dir: frontend

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/course-planner-02/backend:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/course-planner-02/frontend:latest']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'backend-deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    dir: .

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'backend-service.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    dir: .

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'frontend-deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    dir: .

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'frontend-service.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    dir: .

images:
  - 'gcr.io/course-planner-02/backend:latest'
  - 'gcr.io/course-planner-02/frontend:latest'
