steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/course-planner-02/backend:latest', '-f', 'backend/Dockerfile', '.']
    dir: backend

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/course-planner-02/frontend:latest', '-f', 'frontend/Dockerfile', '.']
    dir: frontend

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/course-planner-02/backend:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/course-planner-02/frontend:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'backend', '--image', 'gcr.io/course-planner-02/backend:latest', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'frontend', '--image', 'gcr.io/course-planner-02/frontend:latest', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']

images:
  - 'gcr.io/course-planner-02/backend:latest'
  - 'gcr.io/course-planner-02/frontend:latest'
