services:
  postgres-db:
    container_name: course-planner-postgres
    image: postgres:latest
    ports:
      - '5268:5432'
    environment:
      POSTGRES_PASSWORD: 'postgresPassword'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'course_planner_db'