name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - backend/**

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' 

    - name: Restore dependencies
      run: dotnet restore ./backend

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate Docker with GCP
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/courseplanner-backend:latest ./backend
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/courseplanner-backend:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy courseplanner-backend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/courseplanner-backend:latest \
          --region europe-north1 \
          --platform managed \
          --allow-unauthenticated
