name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate Docker with GCP
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/courseplaner-backend:latest .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/courseplaner-backend:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy courseplaner-backend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/courseplaner-backend:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
