name: Deploy Frontend to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Frontend to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate Docker with GCP
      run: gcloud auth configure-docker

    - name: Build and push Docker image for Frontend
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/courseplanner-frontend:latest ./frontend
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/courseplanner-frontend:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy courseplanner-frontend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/courseplanner-frontend:latest \
          --region europe-north1 \
          --platform managed \
          --allow-unauthenticated
